spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/test_db
    platform: postgres
    username: tester
    password: tester
    hikari:
      data-source-properties:
        rewriteBatchedInserts: true
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: true
    properties:
      hibernate.jdbc.batch_size: 1000
      hibernate.format_sql: true
      hibernate.order_updates: true
      hibernate.order_inserts: true
      hibernate.hibernate.jdbc.batch_versioned_data: true

  redis:
    host: localhost
    port: 6379
logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace
    org.springframework: debug
