spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/new_forest
    platform: postgres
    username: test
    password: test
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: true
    properties:
      hibernate:
        default_schema: public
#  redis:
#    host: localhost
#    port: 6379
logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace

biz:
  is-master : "qwer1234"